package com.hit.fp.core

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers

/*
 * ---------------------------------------------------------------------------
 * DataGenerationSpec.scala
 *
 * Unit tests of the purely functional generator: the reproducibility of the
 * random draws, the size of the produced dataset and the fact that the
 * produced lines are readable by the parser of the pipeline.
 * ---------------------------------------------------------------------------
 */

/**
 * Verifies the pure generator of the synthetic dataset.
 */
class DataGenerationSpec extends AnyFunSuite with Matchers {

  /** Seed shared by every test of this suite. */
  private val seed: Long = 12345L

  /** Number of products generated by the tests. */
  private val productCount: Int = 40

  /** Number of transactions generated by the tests. */
  private val transactionCount: Int = 2000

  test("the same seed always rebuilds the very same dataset") {
    val (firstRun, _) = DataGeneration.generateProducts(10, Rng(seed))
    val (secondRun, _) = DataGeneration.generateProducts(10, Rng(seed))
    firstRun shouldBe secondRun
  }

  test("two different seeds build two different datasets") {
    val (firstRun, _) = DataGeneration.generateProducts(10, Rng(seed))
    val (secondRun, _) = DataGeneration.generateProducts(10, Rng(seed + 1L))
    firstRun should not be secondRun
  }

  test("the drawn numbers stay inside their bounds") {
    val drawn = (0 until 500)
      .foldLeft((List.empty[Int], Rng(seed))) {
        case ((values, generator), _) =>
          val (value, next) = generator.nextInt(10)
          (value :: values, next)
      }
      ._1
    drawn.forall(value => value >= 0 && value < 10) shouldBe true
    drawn.distinct.length should be > 1
  }

  test("the generated products are complete and priced") {
    val (products, _) = DataGeneration.generateProducts(productCount, Rng(seed))
    products.length shouldBe productCount
    products.map(product => product.productId).distinct.length shouldBe
      productCount
    products.forall(product => product.basePrice > 0.0) shouldBe true
  }

  test("the generated transactions refer to existing products") {
    val (products, afterProducts) =
      DataGeneration.generateProducts(productCount, Rng(seed))
    val (transactions, _) = DataGeneration.generateTransactions(
      transactionCount,
      products,
      afterProducts
    )
    val known = products.map(product => product.productId).toSet
    transactions.length shouldBe transactionCount
    transactions.forall(line => known.contains(line.productId)) shouldBe true
    transactions.forall(line => line.quantity > 0) shouldBe true
  }

  test("the sales concentrate on a few categories") {
    val (products, afterProducts) =
      DataGeneration.generateProducts(productCount, Rng(seed))
    val (transactions, _) = DataGeneration.generateTransactions(
      transactionCount,
      products,
      afterProducts
    )
    val categoryOf = products
      .map(product => (product.productId, product.category))
      .toMap
    val sold = transactions
      .groupBy(line => categoryOf(line.productId))
      .map { case (category, lines) => (category, lines.length) }
    val ranked = sold.values.toList.sortBy(count => -count)
    /* The most popular category must clearly beat the least popular one. */
    ranked.head should be > (ranked.last * 3)
  }

  test("the rendered file starts with its header line") {
    val (products, _) = DataGeneration.generateProducts(5, Rng(seed))
    DataGeneration.productLines(products).head shouldBe
      DataGeneration.productHeader
  }

  test("almost every rendered line is readable by the parser") {
    val (products, afterProducts) =
      DataGeneration.generateProducts(productCount, Rng(seed))
    val (transactions, _) = DataGeneration.generateTransactions(
      transactionCount,
      products,
      afterProducts
    )
    val lines = DataGeneration.transactionLines(transactions).tail
    val parsed = lines.map(line => CsvParsing.parseTransaction(line))
    val accepted = parsed.count(result => result.isRight)
    val rejected = parsed.count(result => result.isLeft)
    /* The generator damages a few lines on purpose, but only a few. */
    rejected should be > 0
    accepted.toDouble / lines.length should be > 0.99
  }
}
