package com.hit.fp.model

/*
 * ---------------------------------------------------------------------------
 * Reports.scala
 *
 * Immutable result types produced by the analytical jobs of the pipeline.
 * Every job returns a Dataset of one of these case classes, and every one of
 * them is written to the output directory as a CSV file.
 *
 * Grouping the result types in a single file keeps the model package small
 * and makes the shape of the final report obvious to the reader.
 * ---------------------------------------------------------------------------
 */

/**
 * Aggregated revenue of one commercial category.
 *
 * @param category   commercial category that was aggregated
 * @param revenue    total revenue generated by the category
 * @param orders     number of transaction lines of the category
 * @param unitsSold  number of units sold in the category
 */
final case class CategoryRevenue(
    category: String,
    revenue: Double,
    orders: Long,
    unitsSold: Long
)

/**
 * Aggregated revenue of one destination country.
 *
 * @param country country the orders were shipped to
 * @param revenue total revenue generated by the country
 */
final case class CountryRevenue(country: String, revenue: Double)

/**
 * Total amount spent by one customer.
 *
 * @param customerId identifier of the customer
 * @param totalSpent total revenue generated by the customer
 * @param orders     number of transaction lines of the customer
 */
final case class CustomerSpending(
    customerId: String,
    totalSpent: Double,
    orders: Long
)

/**
 * Number of transaction lines that fall in one order size classification.
 *
 * @param size  label of the classification, see [[OrderSize]]
 * @param count number of transaction lines of that classification
 */
final case class OrderSizeCount(size: String, count: Long)

/**
 * One line of the Pareto analysis of the categories.
 *
 * @param category        commercial category that was aggregated
 * @param revenue         total revenue generated by the category
 * @param cumulativeShare share in percent of the total revenue generated by
 *                        this category and by every richer category
 */
final case class ParetoLine(
    category: String,
    revenue: Double,
    cumulativeShare: Double
)
