package com.hit.fp.core

import scala.annotation.tailrec

import com.hit.fp.model.CategoryRevenue
import com.hit.fp.model.EnrichedTransaction
import com.hit.fp.model.Large
import com.hit.fp.model.Medium
import com.hit.fp.model.OrderSize
import com.hit.fp.model.ParetoLine
import com.hit.fp.model.Premium
import com.hit.fp.model.Product
import com.hit.fp.model.Small
import com.hit.fp.model.Transaction

/*
 * ---------------------------------------------------------------------------
 * PureAnalytics.scala
 *
 * The functional core of the project. Every function of this object is pure:
 * it depends on nothing but its arguments, it mutates nothing, it performs no
 * input/output operation, and calling it twice with the same arguments always
 * returns the same result.
 *
 * Because of that purity the whole analytical logic of the pipeline is unit
 * tested with plain ScalaTest assertions, without a Spark session and without
 * a single file on the disk. The Spark jobs of the spark package only choose
 * how to distribute these functions over the cluster.
 *
 * The object also carries two of the advanced techniques of the project:
 *   TECHNIQUE 3 : tail recursion, see totalRevenue and paretoOf below.
 *   TECHNIQUE 4 : pattern matching with case classes, see classifyOrder.
 * ---------------------------------------------------------------------------
 */

/**
 * Mutation-free accumulator used while a group of transactions is folded.
 *
 * @param revenue revenue accumulated so far
 * @param orders  number of transaction lines accumulated so far
 * @param units   number of units accumulated so far
 */
final case class RevenueAccumulator(
    revenue: Double,
    orders: Long,
    units: Long
)

/**
 * Companion object of [[RevenueAccumulator]] holding its neutral element.
 */
object RevenueAccumulator {

  /** Accumulator of an empty group, the neutral element of the fold. */
  val empty: RevenueAccumulator = RevenueAccumulator(0.0, 0L, 0L)
}

/**
 * Pure analytical functions shared by every job of the pipeline.
 */
object PureAnalytics {

  /** Revenue under which an order is considered to be a small one. */
  private val smallLimit: Double = 50.0

  /** Revenue under which an order is considered to be a medium one. */
  private val mediumLimit: Double = 200.0

  /** Revenue under which an order is considered to be a large one. */
  private val largeLimit: Double = 1000.0

  /** Factor used to round a monetary amount to two decimal digits. */
  private val centsFactor: Double = 100.0

  /**
   * Rounds a monetary amount to two decimal digits.
   *
   * @param amount amount to round
   * @return the rounded amount
   */
  def roundMoney(amount: Double): Double =
    math.round(amount * centsFactor) / centsFactor

  /**
   * Computes the revenue generated by a single transaction.
   *
   * @param transaction transaction to evaluate
   * @return the revenue of the transaction, rounded to two decimal digits
   */
  def revenueOf(transaction: Transaction): Double =
    roundMoney(transaction.quantity * transaction.unitPrice)

  /**
   * Merges a transaction and the product it refers to into a single value.
   *
   * @param transaction transaction to enrich
   * @param product     catalog entry of the purchased product
   * @return the enriched transaction
   */
  def enrich(
      transaction: Transaction,
      product: Product
  ): EnrichedTransaction =
    EnrichedTransaction(
      orderId = transaction.orderId,
      customerId = transaction.customerId,
      productName = product.productName,
      category = product.category,
      country = transaction.country,
      quantity = transaction.quantity,
      unitPrice = transaction.unitPrice,
      revenue = revenueOf(transaction),
      orderDate = transaction.orderDate
    )

  /**
   * Classifies an order according to the revenue it generated.
   *
   * The body is a pattern match with guards over the revenue, and it produces
   * one of the case objects of the sealed [[OrderSize]] trait.
   *
   * @param revenue revenue of the order
   * @return the classification of the order
   */
  def classifyOrder(revenue: Double): OrderSize =
    revenue match {
      case amount if amount < smallLimit => Small
      case amount if amount < mediumLimit => Medium
      case amount if amount < largeLimit => Large
      case _ => Premium
    }

  /**
   * Renders a classification as the sentence shown by the console report.
   *
   * The body is an exhaustive pattern match over the case objects of the
   * sealed trait, therefore the compiler rejects the code as soon as a new
   * classification is added to the model and forgotten here.
   *
   * @param size classification to render
   * @return the human readable description of the classification
   */
  def describeSize(size: OrderSize): String =
    size match {
      case Small => "below " + smallLimit + " dollars"
      case Medium => "between " + smallLimit + " and " + mediumLimit
      case Large => "between " + mediumLimit + " and " + largeLimit
      case Premium => "at least " + largeLimit + " dollars"
    }

  /**
   * Curried predicate that keeps the transactions rich enough to be studied.
   *
   * Applying the first parameter list alone returns a predicate that closed
   * over the threshold. That predicate is the closure the Spark filter jobs
   * ship to the executors.
   *
   * @param threshold   minimal revenue a transaction has to reach
   * @param transaction transaction to test
   * @return true when the transaction reaches the threshold
   */
  def atLeastRevenue(
      threshold: Double
  )(transaction: EnrichedTransaction): Boolean =
    transaction.revenue >= threshold

  /**
   * Curried predicate that keeps the transactions of a set of countries.
   *
   * @param countries   accepted destination countries
   * @param transaction transaction to test
   * @return true when the transaction was shipped to an accepted country
   */
  def shippedTo(
      countries: Set[String]
  )(transaction: EnrichedTransaction): Boolean =
    countries.contains(transaction.country)

  /**
   * Adds one transaction to a running accumulator.
   *
   * @param accumulator accumulator built by the previous transactions
   * @param transaction transaction to add
   * @return the accumulator including the given transaction
   */
  def accumulate(
      accumulator: RevenueAccumulator,
      transaction: EnrichedTransaction
  ): RevenueAccumulator =
    RevenueAccumulator(
      revenue = accumulator.revenue + transaction.revenue,
      orders = accumulator.orders + 1L,
      units = accumulator.units + transaction.quantity
    )

  /**
   * Folds a whole group of transactions into the report of one category.
   *
   * @param category     name of the folded category
   * @param transactions transactions belonging to that category
   * @return the aggregated report of the category
   */
  def foldCategory(
      category: String,
      transactions: Iterator[EnrichedTransaction]
  ): CategoryRevenue = {
    val folded = transactions.foldLeft(RevenueAccumulator.empty)(accumulate)
    CategoryRevenue(
      category = category,
      revenue = roundMoney(folded.revenue),
      orders = folded.orders,
      unitsSold = folded.units
    )
  }

  /**
   * Sums the revenues of a list of transactions with a tail recursion.
   *
   * The recursive call is the very last expression of the function, so the
   * compiler turns the recursion into a loop and the annotation guarantees
   * that a list of any length is summed without overflowing the stack.
   *
   * @param transactions transactions to sum
   * @return the total revenue of the given transactions
   */
  def totalRevenue(transactions: List[EnrichedTransaction]): Double = {
    @tailrec
    def loop(remaining: List[EnrichedTransaction], sum: Double): Double =
      remaining match {
        case Nil => sum
        case head :: tail => loop(tail, sum + head.revenue)
      }

    roundMoney(loop(transactions, 0.0))
  }

  /**
   * Generic higher order selection of the best elements of a list.
   *
   * The function works for any type of element: the caller provides the
   * scoring function, which is exactly what makes it reusable by the customer
   * report and by the category report alike.
   *
   * @param items items to select from
   * @param count number of items to keep
   * @param score function giving the score of an item
   * @tparam A type of the items
   * @return the `count` items having the highest score, best one first
   */
  def topBy[A](items: List[A], count: Int)(score: A => Double): List[A] =
    items.sortBy(item => -score(item)).take(count)

  /**
   * Builds the Pareto analysis of the categories with a tail recursion.
   *
   * The categories are sorted by decreasing revenue and each line carries the
   * share of the total revenue generated by itself and by every category
   * above it, which answers the question "how many categories generate most
   * of the revenue of the shop".
   *
   * @param categories aggregated revenue of every category
   * @return one Pareto line per category, richest category first
   */
  def paretoOf(categories: List[CategoryRevenue]): List[ParetoLine] = {
    val sorted = categories.sortBy(category => -category.revenue)
    val total = sorted.foldLeft(0.0)((sum, entry) => sum + entry.revenue)

    @tailrec
    def loop(
        remaining: List[CategoryRevenue],
        running: Double,
        built: List[ParetoLine]
    ): List[ParetoLine] =
      remaining match {
        case Nil => built.reverse
        case head :: tail =>
          val cumulated = running + head.revenue
          val share = if (total <= 0.0) 0.0 else cumulated / total
          val line = ParetoLine(
            category = head.category,
            revenue = roundMoney(head.revenue),
            cumulativeShare = roundMoney(share * centsFactor)
          )
          loop(tail, cumulated, line :: built)
      }

    loop(sorted, 0.0, Nil)
  }

  /**
   * Counts how many categories are needed to reach a share of the revenue.
   *
   * @param pareto    Pareto lines produced by [[paretoOf]]
   * @param threshold share of the revenue to reach, in percent
   * @return the number of categories needed to reach the given share
   */
  def categoriesUpTo(pareto: List[ParetoLine], threshold: Double): Int =
    if (pareto.isEmpty) 0
    else {
      val below = pareto.takeWhile(line => line.cumulativeShare < threshold)
      math.min(below.length + 1, pareto.length)
    }
}
